services:
  app:
    build: .
    container_name: notes-app
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}

      RABBIT_HOST: ${RABBIT_HOST}
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USERNAME: ${RABBIT_USERNAME}
      RABBIT_PASSWORD: ${RABBIT_PASSWORD}
      RABBIT_STOMP_PORT: ${RABBIT_STOMP_PORT}

#      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
#      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
#      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    networks:
      - notes-network

  postgres:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: notes-db
    environment:
#      POSTGRES_USER: "postgres"
#      POSTGRES_PASSWORD:
#      POSTGRES_DB: "NoteApp"
       DB_USERNAME: ${DB_USERNAME}
       DB_PASSWORD: ${DB_PASSWORD}
       DB_URL: ${DB_URL}
    ports:
      - "5433:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - notes-network

  redis:
    image: redis:7
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    container_name: notes-redis
    command: ["redis-server", "--protected-mode", "no"]
    networks:
      - notes-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_TICK_TIME: "2000"
    networks:
      - notes-network

  kafka:
    image: confluentinc/cp-kafka:6.2.1
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: "1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    #private network bridge
    networks:
      - notes-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: notes-rabbit
    ports:
      - "15672:15672"
    command: >
       sh -c "rabbitmq-plugins enable --offline rabbitmq_stomp &&
              rabbitmq-server"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit memory_high_watermark 0.4"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 15s
      timeout: 10s
      retries: 10
    networks:
      - notes-network

volumes:
  pg-data:

networks:
  notes-network:
    driver: bridge